pub mod audit_middleware;
pub mod auth;
pub mod chroma_client;
pub mod chunking;
pub mod embedding_client;
pub mod error;
pub mod file_validation;
pub mod llm;
pub mod rate_limit;
pub mod rbac;
pub mod types;
pub mod user_context;

pub use auth::{AuthUser, JwtValidator};
pub use chroma_client::ChromaClient;
pub use chunking::chunk_document;
pub use embedding_client::EmbeddingClient;
pub use error::AppError;
pub use file_validation::{validate_file, validate_zip_magic};
pub use llm::LlmClient;
pub use rate_limit::body_limit_layer;
pub use types::{ChromaResult, ChunkData, Embedding, FileType};
